# Generated by Django 6.0.4 on 2026-04-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sueldo', 'Sueldo'), ('propina', 'Propina'), ('extra', 'Otro Ingreso')], max_length=20, verbose_name='Tipo de Ingreso')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto ($)')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Sueldos y Propinas',
            },
        ),
    ]
