# Generated by Django 6.0.4 on 2026-04-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('comida', 'Comida'), ('transporte', 'Transporte'), ('servicios', 'Servicios'), ('varios', 'Varios')], max_length=100)),
            ],
        ),
    ]
