# Generated by Django 6.0.4 on 2026-04-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='gasto',
            name='sub_hogar',
            field=models.CharField(blank=True, choices=[('alquiler', 'Alquiler'), ('wifi', 'WiFi'), ('luz', 'Luz'), ('gas', 'Gas'), ('agua', 'Agua'), ('expensas', 'Expensas'), ('compras_casa', 'Compras de casa')], max_length=20, null=True, verbose_name='Detalle Hogar (Si aplica)'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('hogar', 'Gasto de Hogar'), ('boludo', 'Gasto Boludo'), ('amigos', 'Salida con Amigos'), ('pareja', 'Salida con mi Pareja')], default='hogar', max_length=20, verbose_name='Tipo de Gasto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción / Observaciones'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
