# Generated by Django 6.0.4 on 2026-04-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_remove_gasto_categoria_gasto_sub_hogar_gasto_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='servicio_especifico',
            field=models.CharField(blank=True, choices=[('netflix', 'Netflix'), ('disney', 'Disney+'), ('max', 'Max'), ('prime', 'Amazon Prime Video'), ('paramount', 'Paramount+'), ('apple_tv', 'Apple TV+'), ('star', 'Star+'), ('claro', 'Claro Video'), ('mubi', 'MUBI'), ('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('yt_music', 'YouTube Music'), ('deezer', 'Deezer'), ('dgo', 'DGO'), ('flow', 'Flow'), ('tyc', 'TyC Sports Play'), ('basquet', 'Básquet Pass'), ('nba', 'NBA League Pass'), ('xbox', 'Xbox Game Pass'), ('ps_plus', 'PlayStation Plus'), ('nintendo', 'Nintendo Switch Online')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='sub_boludo',
            field=models.CharField(blank=True, choices=[('golosinas', 'Golosinas'), ('gaseosas', 'Gaseosas'), ('cigarrillos', 'Cigarrillos'), ('galletitas', 'Galletitas'), ('plataformas', 'Plataformas Digitales')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo_plataforma',
            field=models.CharField(blank=True, choices=[('peliculas', 'Películas y Series'), ('musica', 'Música'), ('tv_deportes', 'TV en vivo y Deportes'), ('videojuegos', 'Videojuegos')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='sub_hogar',
            field=models.CharField(blank=True, choices=[('alquiler', 'Alquiler'), ('wifi', 'WiFi'), ('luz', 'Luz'), ('gas', 'Gas'), ('agua', 'Agua'), ('expensas', 'Expensas'), ('compras_casa', 'Compras de casa')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('hogar', 'Gasto de Hogar'), ('boludo', 'Gasto Boludo'), ('amigos', 'Salida con Amigos'), ('pareja', 'Salida con mi Pareja')], max_length=20),
        ),
    ]
