# Generated by Django 6.0.4 on 2026-04-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_gasto_servicio_especifico_gasto_sub_boludo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sueldo', 'Sueldo'), ('propina', 'Propina'), ('extra', 'Otro Ingreso')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
            ],
        ),
    ]
